### ISSUE TITLE
Regarding training setup and GPU hours

### ISSUE THREAD

**Issue by sunny1401** [fcjian/InstaGen#6]
Hi - Thank you for this work. I had a question - I was going through the fine-tuning code. I see that you are using 8 GPUs. Could you tell how long it takes to train the model? Or maybe how long it takes to fine-tune the model on 8GPUs? I missed that information in the paper. I don't have access to 8 GPUs readily so it would help me looking for online solutions. for fine-tuning

**Comment by fcjian** [comment]
@sunny1401 We fine-tune Stable Diffusion on 8 A100, which takes approximately 6 hours.

**Comment by sunny1401** [comment]
Thank you for that information

**Comment by sunny1401** [comment]
Hi - I also wanted to ask - can you please explain your training setup. Because it's failing for me. What I mean by that is like the memory per GPU and if this was distributed training using multi-node setup.

**Comment by fcjian** [comment]
@sunny1401 We use single machine with 8 A100-80G.

**Comment by sunny1401** [comment]
Oh thank you
